// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQyzsy3dfLTIpOCF-mWh_LivvhwyJr5c',
    appId: '1:901534053527:web:29b0ed8ad30fe1de9ea5d2',
    messagingSenderId: '901534053527',
    projectId: 'diary-30f8f',
    authDomain: 'diary-30f8f.firebaseapp.com',
    storageBucket: 'diary-30f8f.appspot.com',
    measurementId: 'G-XMYRVBTTM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnKXxELO3fbkkvCrToYCpivytH9a9eLlw',
    appId: '1:901534053527:android:e8c63c4d7004c9789ea5d2',
    messagingSenderId: '901534053527',
    projectId: 'diary-30f8f',
    storageBucket: 'diary-30f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmKUam7rSjvnAVOVW9IVr3u54GE_ioFyM',
    appId: '1:901534053527:ios:994da390de895fd39ea5d2',
    messagingSenderId: '901534053527',
    projectId: 'diary-30f8f',
    storageBucket: 'diary-30f8f.appspot.com',
    iosClientId: '901534053527-4u5avhgcehighmk20eqocrjaouuf9plq.apps.googleusercontent.com',
    iosBundleId: 'com.example.statefulproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmKUam7rSjvnAVOVW9IVr3u54GE_ioFyM',
    appId: '1:901534053527:ios:994da390de895fd39ea5d2',
    messagingSenderId: '901534053527',
    projectId: 'diary-30f8f',
    storageBucket: 'diary-30f8f.appspot.com',
    iosClientId: '901534053527-4u5avhgcehighmk20eqocrjaouuf9plq.apps.googleusercontent.com',
    iosBundleId: 'com.example.statefulproject',
  );
}
